/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * principal.java
 *
 * Created on 04-abr-2018, 11:57:53
 */


package vista;
import modelo.sucursal;
import modelo.color;
import modelo.talle;
import modelo.prenda;
import modelo.stock;
import modelo.material;
import modelo.solicitud;
import java.util.ArrayList;
import java.util.Arrays;


/**
 *
 * @author fernanda
 */
public class principal extends javax.swing.JFrame {

    public static sucursal Sucursal1;
    public static sucursal Sucursal2;
    public static color ColorBlanco;
    public static color ColorAzul;
    public static color ColorRojo;
    public static color ColorGris;
    public static color ColorVerde;
    public static color ColorNaranja;
    public static talle TalleXS;
    public static talle TalleS;
    public static talle TalleM;
    public static talle TalleL;
    public static talle TalleXL;
    public static prenda Prenda1;
    public static prenda Prenda2;
    public static prenda Prenda3;
    public static prenda Prenda4;
    public static prenda Prenda5;
    public static stock Stock1;
    public static stock Stock2;
    public static stock Stock3;
    public static stock Stock4;
    public static stock Stock5;
    public static material Material1;
    public static material Material2;
    public static material Material3;
    public static material Material4;
    //public static ArrayList<color> Arraycolores;
    public static color[] Arraycolores;
    public static talle[] Arraytalles;
    public static prenda[] Arrayprendas;
    public static material[] Arraymateriales;
    public static solicitud[] Arraysolicitudes;
    public static sucursal[] Arraysucursales;


    /** Creates new form principal */
    public principal() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        CargarDatos();

    }
    
    public void CargarDatos()
    {   
        Sucursal1= new sucursal(1,"sucursal1","direccion1");
        Sucursal2= new sucursal(2,"sucursal2","direccion2");
        ColorBlanco= new color(1,"Blanco");
        ColorAzul= new color(2,"Azul");
        ColorRojo= new color(3,"Rojo");
        ColorGris= new color(4,"Gris");
        ColorVerde= new color(5,"Verde");
        ColorNaranja= new color(6,"Naranja");
        TalleXS = new talle(1,"XS");
        TalleS = new talle(2,"S");
        TalleM = new talle(3,"M");
        TalleL = new talle(4,"L");
        TalleXL = new talle(5,"XL");
        Prenda1 = new prenda(1,"remera",50);
        Prenda2 = new prenda(2,"pantalon",100);
        Prenda3 = new prenda(3,"short",200);
        Prenda4 = new prenda(4,"musculosa",150);
        Prenda5 = new prenda(5,"campera",250);
        Material1 = new material(1,"algodon");
        Material2 = new material(2,"lino");
        Material3 = new material(3,"poliester");
        Material4 = new material(4,"lana");
        Stock1 = new stock(1,Prenda1,TalleS,ColorAzul,Sucursal1,Material1,4);
        Stock2 = new stock(2,Prenda2,TalleXL,ColorGris,Sucursal2,Material2,5);
        Stock3 = new stock(3,Prenda1,TalleM,ColorNaranja,Sucursal1,Material3,3);
        Stock4 = new stock(4,Prenda3,TalleL,ColorVerde,Sucursal2,Material4,7);
        Stock5 = new stock(5,Prenda5,TalleXS,ColorBlanco,Sucursal1,Material1,6);
        Arraycolores = new color[6];
        Arraycolores[0] = ColorAzul;
        Arraycolores[1] = ColorBlanco;
        Arraycolores[2] = ColorRojo;
        Arraycolores[3] = ColorGris;
        Arraycolores[4] = ColorVerde;
        Arraycolores[5] = ColorNaranja;
        Arraytalles = new talle[5];
        Arraytalles[0] = TalleXS;
        Arraytalles[1] = TalleS;
        Arraytalles[2] = TalleM;
        Arraytalles[3] = TalleL;
        Arraytalles[4] = TalleXL;
        Arrayprendas = new prenda[5];
        Arrayprendas[0] = Prenda1;
        Arrayprendas[1] = Prenda2;
        Arrayprendas[2] = Prenda3;
        Arrayprendas[3] = Prenda4;
        Arrayprendas[4] = Prenda5;
        Arraymateriales = new material[4];
        Arraymateriales[0] = Material1;
        Arraymateriales[1] = Material2;
        Arraymateriales[2] = Material3;
        Arraymateriales[3] = Material4;
        Arraysucursales = new sucursal[2];
        Arraysucursales[0] = Sucursal1;
        Arraysucursales[1] = Sucursal2;

       
        
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Realizar solicitud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Solicitudes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Existencias");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(279, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        realizarsolicitud rs = new realizarsolicitud(this,true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        solicitudes s= new solicitudes(this,true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        existencias e= new existencias(this,true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

}
