/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * realizarsolicitud.java
 *
 * Created on 04-abr-2018, 11:47:16
 */

package vista;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import modelo.solicitud;
import modelo.prenda;
import modelo.talle;
import modelo.color;
import modelo.material;
import modelo.lineadesolicitud;
import vista.principal;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author fernanda
 */
public class realizarsolicitud extends javax.swing.JDialog {
        public DefaultTableModel modelo = new DefaultTableModel();
        public static ArrayList<solicitud> Arraysolicitudes = new ArrayList<solicitud>();


    /** Creates new form realizarsolicitud */
    public realizarsolicitud(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String format = formatter.format(date);
        TextFecha.setText(format);

        this.setLocationRelativeTo(parent);
        cargarcolumnas();
        this.cargarcombos();
        this.setVisible(true);
        solicitud nuevasolicitud = new solicitud();
       

        


    }

    private void cargarcolumnas(){
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        modelo.addColumn("Prenda");
        modelo.addColumn("Talle");
        modelo.addColumn("Color");
        modelo.addColumn("Material");
        modelo.addColumn("Cantidad");

        jTable1.setModel(modelo);
    }

    public void cargarcombos(){
        combosucursal.addItem(principal.Sucursal1.getNombre());
        combosucursal.addItem(principal.Sucursal2.getNombre());
        comboprenda.addItem(principal.Prenda1.getCodigo());
        comboprenda.addItem(principal.Prenda2.getCodigo());
        comboprenda.addItem(principal.Prenda3.getCodigo());
        combotalle.addItem(principal.TalleXS.getDescripcion());
        combotalle.addItem(principal.TalleS.getDescripcion());
        combotalle.addItem(principal.TalleM.getDescripcion());
        combotalle.addItem(principal.TalleL.getDescripcion());
        combotalle.addItem(principal.TalleXL.getDescripcion());
        combocolor.addItem(principal.ColorAzul.getDescripcion());
        combocolor.addItem(principal.ColorBlanco.getDescripcion());
        combocolor.addItem(principal.ColorRojo.getDescripcion());
        combocolor.addItem(principal.ColorGris.getDescripcion());
        combocolor.addItem(principal.ColorVerde.getDescripcion());
        combocolor.addItem(principal.ColorNaranja.getDescripcion());
        combomaterial.addItem(principal.Material1.getDescripcion());
        combomaterial.addItem(principal.Material2.getDescripcion());
        combomaterial.addItem(principal.Material3.getDescripcion());
        combomaterial.addItem(principal.Material4.getDescripcion());



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combosucursal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboprenda = new javax.swing.JComboBox();
        combotalle = new javax.swing.JComboBox();
        combocolor = new javax.swing.JComboBox();
        TextFecha = new javax.swing.JTextField();
        textcantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BotonAgregarLineaSolicitud = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        combomaterial = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Realizar solicitud");

        jLabel2.setText("Fecha");

        jLabel3.setText("Sucursal");

        jLabel4.setText("Prenda");

        jLabel5.setText("Talle");

        jLabel6.setText("Color");

        jLabel7.setText("Cantidad");

        TextFecha.setEnabled(false);
        TextFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFechaActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Realizar solicitud");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("SOLICITUDES");

        BotonAgregarLineaSolicitud.setText("Agregar");
        BotonAgregarLineaSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarLineaSolicitudActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("Material");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(combocolor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(combotalle, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(comboprenda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(combosucursal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(combomaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(100, 100, 100))
                                            .addComponent(TextFecha)))
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(BotonAgregarLineaSolicitud))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combosucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combotalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combocolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonAgregarLineaSolicitud)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(28, 28, 28)))
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combomaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(409, 409, 409))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int i,j;
       // Integer prendanueva = 0;
        String tallenuevo = "" ;
        String colornuevo = "";
        String materialnuevo = "";
        int cantidadnuevo = 0;

        for(i=0;i<(jTable1.getRowCount());i++)
        {

            Integer prendanueva = Integer.parseInt(jTable1.getValueAt(i,i+1).toString()); //jTable1.getValueAt(i, i+1);
            tallenuevo = (String) jTable1.getValueAt(i,i+2);
            colornuevo = (String) jTable1.getValueAt(i,i+3);
            materialnuevo = (String) jTable1.getValueAt(i, i+4);
            cantidadnuevo = (Integer) jTable1.getValueAt(i,i+5);

         

        lineadesolicitud linea = new lineadesolicitud();

        for(i=0;i<6;i++)
        {
            if(prendanueva == principal.Arrayprendas[i].getCodigo()){
                linea.setPrenda(principal.Arrayprendas[i]);
            }
            if(tallenuevo == principal.Arraytalles[i].getDescripcion()){
                linea.setTalle(principal.Arraytalles[i]);
            }
            if(colornuevo == principal.Arraycolores[i].getDescripcion()){
                linea.setColor(principal.Arraycolores[i]);
            }
            if(materialnuevo == principal.Arraymateriales[i].getDescripcion()){
                linea.setMaterial(principal.Arraymateriales[i]);
            }
        }
        linea.setCantidad(cantidadnuevo);

        ArrayList<lineadesolicitud> Arraylineas = new ArrayList();
        Arraylineas.add(linea);

        solicitud variablesolicitud = new solicitud();

        variablesolicitud.setFecha(TextFecha.getText());
        Object sucursalnueva = combosucursal.getSelectedItem();

        if(sucursalnueva == principal.Arraysucursales[0]){
            variablesolicitud.setSucursal(principal.Arraysucursales[0]);
          }
 else{
            variablesolicitud.setSucursal(principal.Arraysucursales[1]);
 }
        variablesolicitud.setLineasdesolicitud(Arraylineas);

        // solicitud[] Arraysolicitudes;
     //   ArrayList<solicitud> Arraysolicitudes = new ArrayList();
        Arraysolicitudes.add(variablesolicitud);




        }





    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotonAgregarLineaSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarLineaSolicitudActionPerformed
        // TODO add your handling code here:
        Object[] fila = new Object[5];
        fila[0] = comboprenda.getSelectedItem();
        fila[1] = combotalle.getSelectedItem();
        fila[2] = combocolor.getSelectedItem();
        fila[3] = combomaterial.getSelectedItem();
        fila[4] = textcantidad.getText();

        modelo.addRow(fila);

       
       

    }//GEN-LAST:event_BotonAgregarLineaSolicitudActionPerformed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarLineaSolicitud;
    private javax.swing.JTextField TextFecha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox combocolor;
    private javax.swing.JComboBox combomaterial;
    private javax.swing.JComboBox comboprenda;
    private javax.swing.JComboBox combosucursal;
    private javax.swing.JComboBox combotalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textcantidad;
    // End of variables declaration//GEN-END:variables

}
